### ISSUE TITLE
1.1.3部署问题

### ISSUE THREAD

**Issue by f4ct0r** [D0g3-Lab/H1ve#50]
### New Issue Checklist (自检清单)

- [+] Updated H1ve to the latest version (是否更新到最新版本)
- [+] I have read the [README](https://github.com/D0g3-Lab/H1ve/blob/master/README.md)
- [+] I searched for [existing GitHub issues](https://github.com/D0g3-Lab/H1ve/issues)

### Issue Description (问题描述)
我使用的版本是release版本，1.1.3
![image](https://user-images.githubusercontent.com/8639451/93736576-635f7580-fc13-11ea-8f77-488d10feaa31.png)

通过`docker-compose -f single.yml up -d`通过浏览器无法访问
![image](https://user-images.githubusercontent.com/8639451/93736257-57bf7f00-fc12-11ea-8381-d3783f3abe74.png)
由于网络原因，修改了`single.yml`里的网络地址，修改后如下：
```yaml
version: '3.5'

services:

  main:
    build:
      context: .
      args:
        - WORKDIR=$PWD
    image: h1ve-main
    user: root
    restart: always
    ports:
      - 8000:4000
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/CTFd/access.log
      - ERROR_LOG=/var/log/CTFd/error.log
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      default:
      internal:
      frp_containers:
        ipv4_address: 10.201.0.10

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
       internal:

  frps:
    image: d0g3/h1ve-frp
    # you can build image by yourself if you want.
    # build: ./frp
    restart: always
    volumes:
      - ./frp:/conf/
    ports:
      - 8001:80
    entrypoint:
      - /app/frps
      - -c
      - /conf/frps.ini
    networks:
      frp:
        ipv4_address: 10.200.0.3

  frpc:
    image: d0g3/h1ve-frp
    # you can build image by yourself if you want.
    # build: ./frp
    restart: always
    volumes:
      - ./frp:/conf/
    expose:
      - 7400
    entrypoint:
      - /app/frpc
      - -c
      - /conf/frpc.ini
    networks:
      frp:
        ipv4_address: 10.200.0.4
      frp_containers:

networks:
    default:
    internal:
        internal: true
    frp:
      name: "h1ve_frp"
      driver: bridge
      ipam:
        config:
          - subnet: 10.200.0.0/16
    frp_containers:
        name: "h1ve_frp_containers"
        driver: bridge
        ipam:
          config:
            - subnet: 10.201.0.0/16
```
容器都正常启动，并且访问无日志
![image](https://user-images.githubusercontent.com/8639451/93736500-272c1500-fc13-11ea-9eb7-74cd4595de6f.png)
![image](https://user-images.githubusercontent.com/8639451/93736608-770adc00-fc13-11ea-8e71-a57250329349.png)

### Version & Environment (系统/环境版本)
+ Docker Version: 19.03.12, build 48a66213fe
+ Docker-compose Version: 1.27.2, build unknown
+ Os Version: CentOS Linux release 7.5.1804 (Core)
+ Browser Version: 85.0.4183.102
